### PR TITLE
Some compatibility issues with php 5.3

### PR DESCRIPTION
**Pull request by davidmpaz**
Hello,

Could you please take a look to this, is related to: https://github.com/hakre/XMLReaderIterator/issues/10 This works out some compatibility issues with php 5.3 and test execution. Unfortunately for hhvm I don't know yet what cause the failing.

Thanks in advance.

### CODE REVIEW

**Comment by hakre** [comment]
@davidmpaz: Sorry for have this resting for really three weeks. I'll comile a changeset my own but it should be in the meaning of your pull-request nearly 100%. Feel free to provide more feedback, and sorry for takning so nuch time unltil youi got some feedback.

**Comment by davidmpaz** [comment]
@hakre No problem at all. Thanks for the library, for taking time to check this out and include it in mainstream. Looking forward.
Cheers

**Comment by hakre** [comment]
@davidmpaz: So finally, sorry to have had this laying around for more than three weeks. I've merged that with the changes I had over here and created the travis environment.

So big thanks for your interaction here! All of your suggestions should be in master now. Some have been differently implemented but the overall result should reflect your input well.

I have PHP 5.2 changes shelved, but it's a bit over the top. Just in case you have some interest in it, I pushed those to an extra-branch: `develop-php-5.2`.

I do rebase develop in that project, I perhaps should change that now as you report so much.

Travis works: https://travis-ci.org/hakre/XMLReaderIterator - It's a bit buggy tonight, I tested all PHP versions from 5.3 up to hhvm and nightly (7). hhvm missed bzip2 so there are some problems I didin't fully address in testing and the build fails.

Have fun playing with it and let me know in case you miss something.

**Comment by hakre** [comment]
Just forgot, release is here: https://github.com/hakre/XMLReaderIterator/commit/42da6ef3c2fb839a40cc875aa31596915db758de

**Pull request closed without merging**
